name: autonomous_trust
channels:
  - conda-forge
dependencies:
  - python==3.10.*
  - pip
  - icontract
  - psutil
  - pynacl
  - python-dateutil
  - ruamel.yaml
  - aenum
  - libsass
  - networkx
  - quart==0.18.3
  - numpy
  - dill
  - py-opencv
  - imutils
  - msgpack-numpy
  - geopy
  - utm
  - dash>=2.9.3<=3.0.0
  - dash-bootstrap-components
  - more-itertools==9.0.0
  - jsbeautifier==1.14.3
  - dash-extensions
  - plotly
  - werkzeug==2.2.2
  - flask<=2.2.2
  - flask-caching==2.0.2
  - eventlet
  - absl-py
  - python-flatbuffers
  - python-sounddevice
  - pip:
      - dash-iconify
      - dash-extensions==0.1.12
      - mediapipe
      - websocket
