name: autonomous_trust
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - icontract
  - psutil
  - pynacl
  - python-dateutil
  - ruamel.yaml
  - aenum
  - libsass
  - networkx
  - quart
  - numpy
  - dill
  - py-opencv
  - imutils
  - msgpack-numpy
  - geopy
  - utm
  - dash==2.6.2
  - dash-bootstrap-components
  - plotly
  - werkzeug=2.3.7
  - flask=2.2.2
  - absl-py
  - python-flatbuffers
  - python-sounddevice
  - pip:
      - dash-iconify
      - mediapipe
