name: autonomous_trust
channels:
  - conda-forge
  - forklift
dependencies:
  - python==3.10.*
  - pip
  - icontract
  - psutil
  - pynacl
  - python-dateutil
  - ruamel.yaml
  - protobuf>=20.*
  - libprotobuf
  - aenum
  - libsass
  - networkx
  - quart==0.18.3
  - numpy
  - dill
  - py-opencv
  - imutils
  - msgpack-numpy
  - geopy
  - utm
  - dash==2.14.2
  - dash-bootstrap-components
  - more-itertools==9.0.0
  - jsbeautifier==1.14.3
  - dash-extensions
  - plotly
  - werkzeug==2.2.2
  - flask<=2.2.2
  - flask-caching==2.0.2
  - eventlet
  - absl-py
  - python-flatbuffers
  - python-sounddevice
  - cmake
  - libuuid
  - libsodium
  - pdrops::protobuf-c
  - jansson
  - check
  - cxx-compiler
  - pip:
      - dash-iconify
      - mediapipe
      - websocket
      - parrot-olympe
